#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Apr 16 12:33:39 EEST 2025
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim test_func_synth -key {Post-Synthesis:sim_1:Functional:test} -tclbatch test.tcl -log simulate.log"
xsim test_func_synth -key {Post-Synthesis:sim_1:Functional:test} -tclbatch test.tcl -log simulate.log

